use_frameworks!

platform :ios, '9.0'

target 'UserDetailCategory_Example' do
  pod 'UserDetailCategory', :path => '../'

  target 'UserDetailCategory_Tests' do
    inherit! :search_paths

    
  end
end
